General refactor
elansteam/backend pull request #11
Opened 2023-11-28 06:26 UTC by Spotika

2023-11-28 07:35 UTC, difhel commented on example.env
#12 #13

2023-11-28 07:37 UTC, difhel commented on manage.py
💀

2023-11-28 07:57 UTC, difhel requested changes

2023-11-28 07:57 UTC, difhel commented on src/config.py
#4 не исправлено

2023-11-28 07:57 UTC, difhel commented on src/db/models/role.py
Нет секции Raises в docstring (по GCS): https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2023-11-28 07:57 UTC, difhel commented on src/db/models/user.py
Комментарии на русском

2023-11-28 07:57 UTC, difhel commented on example.env
Но это потом фиксить будем, на ревью ок

2023-11-28 07:57 UTC, difhel commented on src/auth/utils.py
> +    if role_staff % 2 == 1:
Звучит как уязвимость. Я не очень понял, в каком контексте вызывается данная функция, и зачем вообще нужна эта проверка. Если в эту функцию каким-то образом попадет user-controlled значение, он сможет получить полные права в системе

2023-11-28 07:57 UTC, difhel commented on src/auth/utils.py
> +    Returns:
Тут тоже нет Raises

2023-11-28 07:57 UTC, difhel commented on src/db/abstract_database_manager.py
> +
Много отступов

2023-11-28 07:57 UTC, difhel commented on src/db/managers/group_database_manager.py
> +        """
username - изменяемое поле, его **нельзя** использовать как ключ!
используй _id

2023-11-28 07:57 UTC, difhel commented on src/db/models/group_role.py
> +        """
Нет Raises

2023-11-28 07:57 UTC, difhel commented on src/db/oid.py
> +    """Extended ObjectID class with validation"""
Нет Raises

2023-11-28 07:57 UTC, difhel commented on src/routers/groles_router.py
> +"""Endpoints with group roles"""
gnaming #4

2023-11-28 07:57 UTC, difhel commented on src/routers/groups_router.py
> +        return get_error_response(f"Owner with name <{group.owner}> isn`t exist",
doesn't

2023-11-28 07:57 UTC, difhel commented on src/routers/users_router.py
> +        return get_error_response(f"User with user name {user_name} isn`t exist")
doesn't

2023-11-28 08:19 UTC, Spotika commented on src/auth/utils.py
> +    if role_staff % 2 == 1:
> Звучит как уязвимость. Я не очень понял, в каком контексте вызывается данная функция, и зачем вообще нужна эта проверка. Если в эту функцию каким-то образом попадет user-controlled значение, он сможет получить полные права в системе

Это не уязвимость, так как это просто декодирование числа и представление его как роли. Само число берется из базы данных.

2023-11-28 08:28 UTC, Spotika reviewed
All ok, but need to add some doc strings to functions

2023-11-28 18:29 UTC, difhel commented on src/auth/utils.py
~what the fucking fuck~
lgtm

2023-11-28 18:45 UTC, difhel requested changes

2023-11-28 18:45 UTC, difhel commented on src/db/models/role.py
raises

2023-11-28 18:45 UTC, difhel commented on src/db/models/user.py
Русский для солнышек

2023-11-28 20:33 UTC, Spotika commented on src/db/managers/group_database_manager.py
> +        """
Добавлю отдельный метод для поиска по id и он будет использован во всем проекте. get_by_name только для фронтенда

2023-11-28 20:52 UTC, Spotika reviewed
everything is fine, but the system needs to be improved and all TODOs need to be completed

2023-12-09 16:02 UTC, difhel requested changes

2023-12-09 16:02 UTC, difhel commented on src/routers/groups_router.py
> +    await db.group_role.create(GroupRole.model_validate(
g naming #4

2023-12-09 16:02 UTC, difhel commented on src/routers/groups_router.py
> +                       Permissions.C_ADD_USER_TO_GROUP
remove this kind of zvezdec

2023-12-09 16:02 UTC, difhel commented on testing/util_test.py
> +])
Zvezdec.

2023-12-09 16:58 UTC, difhel approved these changes
lgtm

2023-12-09 16:59 UTC, merged