Difhel refactor
elansteam/backend pull request #21
Opened 2023-12-16 12:51 UTC by difhel

Here are some updates made in this branch:
- removed MongoDB ObjectID from all models
- ids of `User` and `Group` are now integers; ids of `GroupRole`, `Role` and `Entity` (domain) are now strings
- `GroupRole` id looks like that: `group<associated_group_id>_<local_group_name>`
- added `mypy` and `ruff` linting (run `python3 manage.py lint`)
- now logger in the CLI shows the name of the running linter
- refactored CLI: added subparses, better documentation (`python3 manage.py -h`), `--config` parameter is now required, but only for `lint` and `run` command
- CLI command `runserver` renamed to `run`
- `pytest`, `pylint`, `ruff` and `mypy` dependencies moved to dev dependencies in `pyproject.toml` (poetry configuration file) - they are not necessary for running server
- created ~`NameRouter`~ `Domain Router` (`NameRouter` was renamed)
- wrote module `utils.regex_validators` for email validation
- new logic in sign in method: user can use his username (e.g. `scintilla_aaa`), id (e.g. `id42`) or email (e.g. `test@difhel.dev`)
- all submodules now have well-formed `__init__.py` files (this is step following PEP-8 and fixing `mypy`-detected issues)
- many methods in the database models were renamed
- deleted adressing by names (domains) - now using only ids (closes #16 )
- fixed #15 
- now CLI `run` command crashes with error description if user provides example.env as his config

2023-12-16 12:53 UTC, difhel commented
Please note that these changes are breaking and they should be fixed before merging with master.
**This is significantly important.**

But I suggest not to implement testing with `pytest` in this pull request and implement that later.

2024-01-31 21:37 UTC, Spotika requested changes

2024-01-31 21:37 UTC, Spotika commented on src/db/managers/user_database_manager.py
> +    async def delete_role(self, user_id: int, role_id: str) -> None:
Протестировать это

2024-01-31 21:37 UTC, Spotika commented on src/routers/auth_router.py
> +async def signup(user: UserSignup):
В этом методе отсутствует удаление сущности, если при создании пользователя произошла ошибка

2024-01-31 21:37 UTC, Spotika commented on src/routers/roles_router.py
> +        return get_error_response(f"Role with id <{role_id}> already exists")
Сюда нужно добавить логирование и вместо такой ошибки сделать статус в upper case

2024-02-01 07:33 UTC, Spotika commented on src/db/managers/user_database_manager.py
> +    async def delete_role(self, user_id: int, role_id: str) -> None:
Так же отсутствует метод в api который предоставляет к этому доступ

2024-02-01 08:13 UTC, Spotika submitted a review, later dismissed
It works and looks pretty good

2024-02-01 11:00 UTC, difhel commented on src/auth/utils.py
> +    if role_staff % 2 == 1:
TODO: delete $2^0$

2024-02-01 12:56 UTC, difhel commented on src/auth/utils.py
> +class AuthException(Exception):
TODO: fix _naming in AuthException (shadow name out of scope)

2024-02-01 12:57 UTC, difhel commented on src/config.py
> +    if any(arg_value is None for arg_value in [
Сделать бананы адекватными

2024-02-01 12:59 UTC, difhel commented on src/db/__init__.py
> +user: UserDatabaseManager = UserDatabaseManager()
Remove typings

2024-02-01 13:28 UTC, difhel commented on src/db/models/role.py
> +def role_name_to_id(role_name: str) -> str:
ID роли должен назначаться пользователем

2024-02-01 13:33 UTC, difhel reviewed
как там это... lgbt

2024-02-01 14:13 UTC, difhel reviewed
lgtm

2024-02-01 14:18 UTC, Spotika approved these changes
~~difhel sucks~~ 
~~lgbt~~ 
**LGTM**

2024-02-01 14:18 UTC, merged

2024-02-02 08:09 UTC, Spotika commented on src/auth/utils.py
> +    if role_staff % 2 == 1:
Fixed now